name: Build and deploy Node.js app to Azure Web App - health-center

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present

      - name: Create artifact archive
        run: |
          zip -r artifact.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip -o ${{ github.workspace }}/node-app/artifact.zip -d ${{ github.workspace }}/node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'health-center'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6EBDA309459D413A956EF317F05CD420 }}
          package: ${{ github.workspace }}/node-app
